// <auto-generated />
using System;
using EquiLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(EquiLinkDbContext))]
    partial class EquiLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquiLink.Domain.Aggregates.Fund.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("manager_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_funds_name");

                    b.ToTable("funds", (string)null);
                });

            modelBuilder.Entity("EquiLink.Domain.Aggregates.Fund.FundRiskLimitTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ConcentrationLimit")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("concentration_limit");

                    b.Property<decimal>("DailyLossLimit")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("daily_loss_limit");

                    b.Property<decimal>("MaxOrderSize")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("max_order_size");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("template_name");

                    b.HasKey("Id");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("uq_fund_risk_limit_templates_name");

                    b.ToTable("fund_risk_limit_templates", (string)null);
                });

            modelBuilder.Entity("EquiLink.Domain.Aggregates.Fund.FundRiskLimits", b =>
                {
                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid")
                        .HasColumnName("fund_id");

                    b.Property<decimal>("ConcentrationLimit")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("concentration_limit");

                    b.Property<decimal>("DailyLossLimit")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("daily_loss_limit");

                    b.Property<decimal>("MaxOrderSize")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("max_order_size");

                    b.HasKey("FundId");

                    b.ToTable("fund_risk_limits", (string)null);
                });

            modelBuilder.Entity("EquiLink.Infrastructure.Persistence.EventStore.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uuid")
                        .HasColumnName("fund_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_order_events_aggregate_id");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique()
                        .HasDatabaseName("uq_order_events_aggregate_version");

                    b.ToTable("order_events", (string)null);
                });

            modelBuilder.Entity("EquiLink.Domain.Aggregates.Fund.FundRiskLimits", b =>
                {
                    b.HasOne("EquiLink.Domain.Aggregates.Fund.Fund", null)
                        .WithOne("RiskLimits")
                        .HasForeignKey("EquiLink.Domain.Aggregates.Fund.FundRiskLimits", "FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquiLink.Domain.Aggregates.Fund.Fund", b =>
                {
                    b.Navigation("RiskLimits")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
